---
title: "Text analizes classs"
author: "Kristóf Menyhért"
date: "2018-02-21"
output: html_document
---

## Coding example:

In this exercise I am presenting an example what can you do with the gutenberg packages.

1st, Load some packages:
```{r, warning=FALSE, message=FALSE}
library(gutenbergr)
library(tidytext)
library(tidyverse)
library(ggplot2)
```

Get Mark Twain's Tom Sawer:

```{r}
mark_twain <- gutenberg_works(author == "Twain, Mark", str_detect(title, "The Adventures of Tom Sawyer"))
```

We should look for the id:

```{r}
head(mark_twain[, c("title", "gutenberg_id")])
```

In this case the id is 74.

Find another book:

```{r}
agatha_christie <- gutenberg_works(str_detect(author, "Agatha"))

head(agatha_christie)
```

Download both of the book:

```{r}
books <- gutenberg_download(c(74, 1155), meta_fields = "title")
```

Use the unnest tokens fuction to split it to words:
```{r}
words <- books %>% unnest_tokens(word, text) %>% anti_join(stop_words)

head(words)
```

```{r}
word_counts <- words %>%
  count(title, word, sort = TRUE)

head(word_counts, 10)
```

```{r}
word_counts %>% 
  filter(n > 50, title == "The Adventures of Tom Sawyer") %>%
  mutate(word = reorder(word,n)) %>%
  ggplot(aes(word, n)) + geom_col() + coord_flip()
```
```{r}
word_counts %>% 
  filter(n > 75, title == "The Secret Adversary") %>%
  mutate(word = reorder(word,n)) %>%
  ggplot(aes(word, n)) + geom_col() + coord_flip()
```

Count frequencies:

```{r}
word_counts2 <- word_counts %>%
  group_by(title) %>%
  mutate(proportion = n / sum(n)) %>%
  select(-n) %>%
  spread(title, proportion)

head(word_counts2, 10)
```
```{r, warning=FALSE, message=FALSE}
filtered_word_counts <-  word_counts2[word_counts2[,2] > 0.01, ]

ggplot(word_counts2, aes(x = word_counts2[,2], y = word_counts2[,3])) + geom_abline(slope =1, linetype=3) + labs(title = paste(c("Word frequincies of:", colnames(word_counts2)[2], "vs",colnames(word_counts2)[3]), collapse = " "), x = colnames(word_counts2)[2], y = colnames(word_counts2)[3]) + geom_text(aes(label = word), color = "blue", alpha = 0.3) + scale_x_continuous(limits = c(0, 0.01))
```
